### ISSUE TITLE
Spoom bump sometimes deletes empty lines

### ISSUE THREAD

**Issue by atanbt** [Shopify/spoom#118]
**Describe the bug**
When I run spoom bump sometimes it will delete the line between the sigil and the first line of the class. For example, of 28 files that it changed when I just ran it, 4 of them the sigil was unchanged but the line was deleted.

**To Reproduce**
Spoom version: 1.1.8

Run spoom bump

**Expected behavior**
It should only change files when there is a sigil change.

**Comment by Morriar** [comment]
👋 Hey Alex,

Do you have a repo I can use to reproduce this problem?

Thanks

**Comment by atanbt** [comment]
Hi @Morriar, unfortunately I don't. I've been seeing the issue in a private repo.

**Comment by Morriar** [comment]
Is it always the same 4 files that get mangled? If yes, any change you can share their contents with me?
