### ISSUE TITLE
Dependencies under `vendor/` affect test output

### ISSUE THREAD

**Issue by KaanOzkan** [Shopify/spoom#239]
**Describe the bug**
Dependencies under `vendor/` affect test output. Failing the expectations if there are any gems.

**To Reproduce**
Spoom version: main

1. Set global bundle config to store gems under `vendor/bundle`: `bundle config set path 'vendor/bundle`
2. `bin/test test/spoom/cli/cli_test.rb`
3. Output contains the dependencies under `vendor/bundle` of the test project

**Expected behavior**
Bundle path shouldn't affect the spoom execution of the `TestProject`.

**Comment by KaanOzkan** [comment]
@swiknaba That is a different error indeed. I'm not sure about the platform specific difference but the initial error makes sense.

Spoom doesn't use `--ignore` flag. You need to specify it as a string argument to the `sorbet_options` flag https://github.com/Shopify/spoom/blob/f85eeac6809aa15ac7082a6c0a3f83ef7e1665fd/lib/spoom/cli/run.rb#L25

It's meant to be used alongside Sorbet config. So easier thing to do is to add `--ignore=vendor/` to your `sorbet/config` file and spoom will pick it up.

**Comment by Morriar** [comment]
I think this was fixed by https://github.com/Shopify/spoom/pull/308. I'm closing for now, let me know if this happens again.
