### ISSUE TITLE
Spoom should raise if it can't produce snapshot metrics

### ISSUE THREAD

**Issue by Morriar** [Shopify/spoom#259]
If the Sorbet process gets killed while processing the metrics, Spoom will just return a bunch of metrics at 0s leaving the user clueless that something went terribly wrong.

* [`Sorbet.srb_metrics`](https://github.com/Shopify/spoom/blob/main/lib/spoom/sorbet.rb#L96-L109) doesn't check for the command status will just return `nil` if it can't read the metrics file (we should make it raise).
* [`Coverage.snapshot`](https://github.com/Shopify/spoom/blob/main/lib/spoom/coverage.rb#L45-L46) will just return an empty `Snapshot` (so all values at `0`) if the metrics object returned by `srb_metrics` is `nil` (we should make it bubble the exception).

**Comment by bitwise-aiden** [comment]
Closed by above PR chain
