### ISSUE TITLE
`bin/spoom bump` failing to find `srb` in CI

### ISSUE THREAD

**Issue by DougEdey** [Shopify/spoom#349]
**Describe the bug**

I'm trying to add `spoom bump --from false --to true --dry` in CI to encourage developers to bump files that they accidentally/incidentally increased the sigil level on.

But it's failing to find sorbet in CI, it's running totally fine in Local Dev.

We're running in GitLab CI if that helps to provide any clarity

Without any options:

```
$ bin/spoom config
Found Sorbet config at sorbet/config.
Paths typechecked:
 * .
Paths ignored:
 * tmp/
 * vendor/
 * scripts/bulk_repos/mk_bulk_gitlab_repos.rb
Allowed extensions:
 * .rb (default)
 * .rbi (default)
$ bin/spoom bump --from false --to true --dry
Checking files...
bundler: command not found: srb
Install missing gem executables with bundle install
```

If I try and provide the binstub location:

```
$ bin/spoom config
Found Sorbet config at sorbet/config.
Paths typechecked:
 * .
Paths ignored:
 * tmp/
 * vendor/
 * scripts/bulk_repos/mk_bulk_gitlab_repos.rb
Allowed extensions:
 * .rb (default)
 * .rbi (default)
$ bin/spoom bump --from false --to true --dry --sorbet "./bin/srb tc"
Checking files...
/usr/local/bundle/gems/bundler-2.4.5/lib/bundler/source/git.rb:208:in rescue in load_spec_files': https://github.com/OpsLevel/active_model_serializers (at v0.10.9-namespace-patch-rails-6-1@c0681c4) is not yet checked out. Run bundle install first. (Bundler::GitError)
```

It feels like I'm missing something obvious here but I'm not sure what...

**To Reproduce**
Spoom version: '1.2.1'

**Expected behavior**

Spoom works in CI.

**Comment by DougEdey** [comment]
From some further debugging, the issue is that we don't install our gems in the default location (due to the way we implemented caching) which meant the fix was:

Where `./vendor` is our gem cache path.

```
bundle exec spoom bump --from false --to true --dry --sorbet "bundle config set --local path './vendor' && bundle exec srb tc"
```

I'm going to close this issue in case other people encounter a similar issue.

**Comment by jplaisted** [comment]
```
$ env  | sort | grep BUNDLE
BUNDLER_VERSION=2.2.33
BUNDLE_APP_CONFIG=/usr/local/bundle
BUNDLE_GEM__FURY__IO=***
BUNDLE_PATH=/usr/local/bundle
BUNDLE_SILENCE_ROOT_WARNING=1
$ env | sort | grep GEM
BUNDLE_GEM__FURY__IO=***
GEM_HOME=/usr/local/bundle
RUBYGEMS_VERSION=3.2.32
$ env | sort | grep RUBY
RUBYGEMS_VERSION=3.2.32
RUBY_DOWNLOAD_SHA256=88cc7f0f021f15c4cd62b1f922e3a401697f7943551fe45b1fdf4f2417a17a9c
RUBY_MAJOR=3.0
RUBY_VERSION=3.0.3
```

**Comment by DougEdey** [comment]
I think you want to run:

```
bundle exec spoom bump --from false --to true --dry --sorbet "bundle config set --local path '/usr/local/bundle' && BUNDLE_APP_CONFIG=/usr/local/bundle bundle exec srb tc"
```

`Bundle.with_unbundled_env` removes all the `BUNDLE_` prefixed env vars so you'll need to recreate the settings (I'm not sure if you need `BUNDLE_APP_CONFIG` but play around and see which of the env vars gets you healthy
