### ISSUE TITLE
Spoom bump from true to strict causing typechecking errors in Shopify core

### ISSUE THREAD

**Issue by patlai** [Shopify/spoom#50]
**Describe the bug**
When trying to bump subscription contract types in  from `typed: true` to `typed: strict`, typing errors are encountered with `dev tc` despite Spoom not bumping sigils automatically for files that would cause typing errors

**To Reproduce**
Spoom version: '1.0.6'
1. Update the spoom gem to version `1.0.6` in Shopify core
2. `cd` into `components/sales/subscriptions/app` on core
3. Run `bundle exec spoom bump --from true --to strict`
4. Run `dev tc` or `spoom tc -s` in core's root directory and see typechecking errors

**Expected behavior**
Spoom should only automatically bump sigils for files that would not cause typing errors without the `-f` option

**Comment by Morriar** [comment]
Fixed by #51.
