### ISSUE TITLE
Add `assert_rbi_exists?` to support wildcard

### ISSUE THREAD

**Issue by KaanOzkan** [Shopify/spoom#614]
Using project assertions with RBI's is common in Tapioca and allowing `assert_rbi_exists?("sorbet/rbi/gems/foo@*.rbi")` would be beneficial so that we can omit the version number.

Maybe we can first check if the given string is a file. If not we can also search the directory with the given path which will support the wildcard out of the box `Dir["sorbet/rbi/gems/foo@*.rbi"]`

I thought this is mostly for RBIs so I'm suggesting a new method but we could also modify the existing `assert_project_file_exist`.
Related PR where we had to update an assertion https://github.com/Shopify/tapioca/pull/2046

**Comment by Morriar** [comment]
This may be better suited for https://github.com/Shopify/tapioca/blob/main/spec/spec_with_project.rb#L87? This is where we define all the custom assertions used in Tapioca test suite.
