### ISSUE TITLE
Run spoon on a subset of folders

### ISSUE THREAD

**Issue by leifg** [Shopify/spoom#97]
Spool looks very promising for running continuously.

However if you install all your gems in your project folder (`bundle install --path vendor/bunlde`) the strictness map in the report html is overshadowed by the gems folder and your actual project files are almost invisible.

Is there a way to exclude or include certain folders for the report generation?

**Comment by Morriar** [comment]
👋 Hey Leif,

The strictness map is built by [reading the Sorbet config file](https://github.com/Shopify/spoom/blob/master/lib/spoom/coverage.rb#L89) and [should already exclude the paths](https://github.com/Shopify/spoom/blob/df338b82e8ca709e79aa670b1b49d22c7cf94bf2/lib/spoom/sorbet.rb#L53-L57) listed with `--ignore` in your config.

Do you have something like `--ignore vendor/bundle` in your `sorbet/config` file?

**Comment by leifg** [comment]
That did indeed work, had a typo in the ignore path.

Thank you for steering me in the right direction!
